# Required
version: 2

conda:
  environment: environment_docs.yaml

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

python:
   version: 3.8  # will be ignored
   install:
      - methods: setuptools
        path: docs/_pytorch_sphinx_theme