name: decode_cpu

channels:
  - haydnspass
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - click
  - cmake=3.15
  - deprecated
  - dotmap
  - h5py
  - intel-openmp
  - jupyter_contrib_nbextensions
  - jupyterlab
  - nb_conda
  - matplotlib
  - ninja
  - numpy
  - opencv
  - pandas
  - pybind11>=2.4
  - python=3.8
  - pytorch>=1.5.1
  - pyyaml
  - pytest
  - pytest-repeat
  - requests
  - scikit-image
  - scikit-optimize
  - scipy
  - seaborn
  - setuptools
  - scikit-image
  - scikit-learn
  - spline
  - sqlite
  - tensorboard
  - tifffile
  - torchvision
  - tqdm
