name: deepsmlm_deployed
channels:
  - pytorch
  - anaconda
  - conda-forge
  - anaconda-fusion
  - defaults

dependencies:
  - bokeh
  - intel-openmp
  - jupyter_contrib_nbextensions
  - jupyterlab
  - nb_conda
  - matplotlib
  - numpy
  - opencv
  - pillow
  - python=3.6
  - pytorch=1.1.0
  - pytest
  - pywavelets
  - scikit-image
  - scipy
  - seaborn
  - setuptools
  - scikit-learn
  - snakeviz
  - sqlite
  - torchvision
  - tqdm
