name: deepsmlm_deployed_new
channels:
  - pytorch
  - conda-forge
  - anaconda
  - anaconda-fusion
  - comet_ml
  - pyviz
  - defaults

dependencies:
  - bokeh
  - comet_ml
  - cudatoolkit=10.0
  - holoviews
  - intel-openmp
  - jupyter_contrib_nbextensions
  - jupyterlab
  - nb_conda
  - matplotlib
  - nodejs
  - numpy
  - opencv
  - pillow
  - python=3.6
  - pytorch=1.2.*
  - pytest
  - pywavelets
  - scikit-image
  - scipy
  - seaborn
  - setuptools
  - scikit-learn
  - snakeviz
  - sqlite
  - tensorflow
  - tensorboard
  - tifffile
  - tikzplotlib
  - torchvision
  - tqdm
