name: deepsmlm_source
channels:
  - haydnspass
  - pytorch
  - conda-forge
  - anaconda
  - anaconda-fusion
  - pyviz
  - defaults

dependencies:
  - bokeh
  - click
  - cmake=3.15
  - comet_ml
  - cudatoolkit=10.1
  - comet_ml
  - deprecated
  - dotmap
  - holoviews
  - h5py
  - intel-openmp
  - jupyter_contrib_nbextensions
  - jupyterlab
  - nb_conda
  - matplotlib
  - nodejs
  - numpy
  - opencv
  - pandas
  - pillow
  - pyyaml
  - pybind11>=2.4
  - python=3.8
  # - pytorch=1.2.*
  - ninja
  - pyyaml
  - mkl
  - mkl-include
  - setuptools
  - spline
  - cffi
  - magma-cuda101

  - pytest
  - pytest-repeat
  - pywavelets
  - scikit-image
  - scipy
  - seaborn
  - setuptools
  - scikit-learn
  - snakeviz
  - spline
  - sqlite
  - tensorflow
  - tensorboard>=1.14
  - tifffile
  - tqdm
