name: decode_cuda

channels:
  - turagalab
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # for building (decode and splinepsf)
  - bump2version
  - cmake=3.15
  - ninja
  - pybind11>=2.4

  # actual package
  - python=3.8
  - pytorch=1.6
  - cudatoolkit=10.2
  - torchvision
  - click
  - deprecated
  - h5py
  - matplotlib
  - pandas
  - pytest
  - pyyaml
  - requests
  - scipy
  - seaborn
  - scikit-image
  - scikit-learn
  - spline
  - tensorboard
  - tifffile
  - tqdm

  # jupyter
  - jupyter_contrib_nbextensions
  - jupyterlab
  - nb_conda
