name: deepsmlm_cuda_py38_pt14

channels:
  - haydnspass
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - click
  - cmake=3.15
  - comet_ml
  - cudatoolkit=10.1
  - deprecated
  - dotmap
  - h5py
  - hyperopt
  - intel-openmp
  - jupyter_contrib_nbextensions
  - jupyterlab
  - nb_conda
  - matplotlib
  - ninja
  - numpy
  - pandas
  - pybind11>=2.4
  - python=3.8
  - pytorch=1.4.*
  - pyyaml
  - pytest
  - pytest-repeat
  - pyspark
  - requests
  - scikit-image
  - scikit-optimize
  - scipy
  - seaborn
  - setuptools
  - scikit-learn
  - sqlite
  - spline
  - tensorboard
  - tifffile
  - torchvision
  - tqdm