name: decode_docs
channels:
  - haydnspass
  - pytorch
  - conda-forge

dependencies:
  - python>=3.8
  - decode
  - recommonmark  # markdown for sphinx
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme
