name: deepsmlm_cpu
channels:
  - pytorch
  - conda-forge
#  - anaconda
#  - anaconda-fusion
  - comet_ml
#  - pyviz
  - defaults

dependencies:
  - click
  - cmake=3.15
  - comet_ml
  - deprecated
  - dotmap
  - h5py
  - intel-openmp
  - jupyter_contrib_nbextensions
  - jupyterlab
  - nb_conda
  - matplotlib
  - ninja
  - numpy
  - opencv
  - python=3.8
  - pytorch=1.4.*
  - pyyaml
  - pytest
  - pytest-repeat
  - scikit-image
  - scipy
  - seaborn
  - setuptools
  - scikit-learn
  - sqlite
  - tifffile
  - torchvision
  - tqdm
