package:
  name: deepsmlm
  version: "0.1.dev"

source:
    git_url: https://github.com/Haydnspass/DeepSMLM
    git_rev: dev_training_engine
    git_depth: 1
    # - path: ~/RemoteDeploy/DeepSMLM
    # - path: ~/Repositories/deepsmlm

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python }}
    - cmake >=3.14
    - ninja
    - setuptools

  host:
    - python {{ python }}
    - numpy {{ numpy }}
    - pybind11 >=2.4
    - cudatoolkit-dev # [linux]

  run:
    - {{ pin_compatible('python', max_pin='x.x') }}
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - cudatoolkit=10.1  # [linux]
    - dotmap
    - pytorch=1.4
    - torchvision
    - click
    - deprecated
    - dotmap
    - h5py
    - joblib
    - matplotlib
    - pytest
    - pyyaml
    - scipy
    - seaborn
    - scikit-learn
    - tifffile
    - tqdm

  test:
    requires:
      - pytest
      - wget
    commands:
      - wget -O {{ SRC_DIR }}/deepsmlm/test/assets/bead_cal_for_testing.mat https://oc.embl.de/index.php/s/YXUydyaXLlKc3UY/download
      - pytest --pyargs deepsmlm

about:
    home: https://rieslab.de
    # dev_url: github url 
    # doc_url: doc url
    # license: GPL-3.0
    # license_family: GPL
    # license_file: {{ SRC_DIR }}/LICENSE
    summary: "bla"
    description: "bla"
