
target_platform:
    - osx-64                           # [osx]
    - linux-64                         # [linux]
    - win-64                           # [win]

python:
    - 3.6
    - 3.7
    - 3.8

numpy:
    - 1.18
