CameraPreset:
Camera:
  baseline: 100.0
  convert2photons: true
  e_per_adu: 45.0
  em_gain: 300.0
  px_size:
  - 100.0
  - 100.0
  qe: 1.0
  read_sigma: 74.4
  spur_noise: 0.002
Evaluation:
  dist_ax: 500.0
  dist_lat: 250.0
  dist_vol:
  match_dims: 3
Hardware:
  device: cuda
  device_ix: 0
  device_simulation: cuda
  num_worker_train: 4
  torch_threads: 4
  unix_niceness: 0
  torch_multiprocessing_sharing_strategy:  # if you get multiprocessing errors, increase ulimit or set to 'file_system'
HyperParameter:
  arch_param:
    activation: ReLU
    depth:
    depth_shared: 2
    depth_union: 2
    depth_bg:
    init_custom: true
    initial_features: 48
    initial_features_bg:
    inter_features: 48
    norm:
    norm_bg:
    norm_bg_groups:
    norm_groups:
    norm_head:
    norm_head_groups:
    p_dropout:
    pool_mode: StrideConv
    upsample_mode: nearest
    recpt_bg:
    skip_gn_level:
    up_mode: upsample
    use_last_nl:
  architecture: SigmaMUNet
  batch_size: 10
  channels_in: 3
  channels_out:
  chweight_stat:
    - 1.0
    - 0.0
  disabled_attributes:
  ds_lifetime:
  epoch_0:
  epochs: 10000
  fgbg_factor:
  grad_mod: true
  emitter_label_photon_min: 100.0
  loss_impl: MixtureModel
  learning_rate_scheduler: StepLR
  learning_rate_scheduler_param:
    step_size: 10
    gamma: 0.9
  max_number_targets: 250
  moeller_gradient_rescale: false
  opt_param:
    lr: 0.0006
    weight_decay: 0.1
  optimizer: AdamW
  photon_threshold:
  pseudo_ds_size: 10000
InOut:
  calibration_file: data/Calibration/Paper/deepSTORM_Ref_AS-Exp_100nm_3dcal.mat  # cubic spline coefficients
  experiment_out: network/2020-07-06  # main output dir
  model_init:
PostProcessing: LookUp  # (blank) for no post-processing or LookUp, Consistency
PostProcessingParam:
  raw_th: 0.5
Scaling:  # if some values are missing they will be auto-set as described in the comment
  input_scale:  # intensity_mu / 50
  input_offset:  # bg_uniform (mean)
  bg_max:  # 1.2 * upper limit of bg val
  phot_max:  # intensity_mu + 8 * sigma
  z_max:  # 1.2 * upper simulation extent
Simulation:
  bg_uniform: 90.0
  density:
  emitter_av: 20
  emitter_extent:
  - - -0.5
    - 39.5
  - - -0.5
    - 39.5
  - - -750
    - 750
  img_size:
  - 40
  - 40
  intensity_mu_sig:
  - 10000.0
  - 3000.0
  intensity_th:
  lifetime_avg: 2.0
  mode: acquisition  # acquisition / samples
  photon_range:
  psf_extent:
  - - -0.5
    - 39.5
  - - -0.5
    - 39.5
  -
  roi_size:  # if none, take the whole range of calibration
  roi_auto_center: false
  xy_unit: px
TestSet:
  mode:  simulated  # static / simulated
  test_size: 512
  frame_extent:
  - - -0.5
    - 39.5
  - - -0.5
    - 39.5
  - null
  img_size:
    - 40
    - 40

