Camera:
  baseline: 100.0
  convert2photons: false
  e_per_adu: 45.0
  em_gain: 300.0
  px_size:
  - 100.0
  - 100.0
  qe: 1.0
  read_sigma: 74.4
  spur_noise: 0.002
Evaluation:
  dist_ax: null
  dist_lat: 150.0
  dist_vol: null
  match_dims: null
Hardware:
  cuda_ix: '0'
  device: cuda
  num_worker_sim: 12
  torch_threads: 1
  unix_niceness: 20
HyperParameter:
  arch_param:
    activation: nn.ReLU()
    depth: 2
    depth_bg: 2
    initial_features: 64
    initial_features_bg: 32
    inter_features: 64
    norm: 'GroupNorm'
    norm_bg: null
    norm_bg_groups: null
    norm_groups: 32
    norm_head: null
    norm_head_groups: null
    p_dropout: null
    pool_mode: StrideConv
    recpt_bg: null
    skip_gn_level: null
    up_mode: upsample
    use_last_nl: true
  architecture: SimpleSMLMNet
  batch_size: 32
  bg_perlin_prob_disable: 0.5
  ch_static_scale:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  channels_in: 3
  channels_out: 6
  ds_lifetime: 0
  dynamic_weight: false
  epoch_0: null
  epochs: 1000
  fgbg_factor: 2.0
  moeller_gradient_rescale: false
  opt_param:
    lr: 0.002
    weight_decay: 0.01
  optimizer: AdamW
  photon_threshold: null
  predict_bg: true
  pseudo_ds_size: 256
  suppress_post_processing: false
  target_roi_size: 3
  test_size: 256
  weight_base: constant
InOut:
  calibration_file: data/Calibration/SMLM Challenge Beads/Coefficients Big ROI/AS-Exp_100nm_3dcal.mat
  data_set: online
  model_init: null
  model_out: network/debug.pt
  root: /Users/lucasmueller/Repositories/DeepSMLM/
LearningRateScheduler:
  cooldown: 10
  factor: 0.5
  mode: min
  patience: 20
  threshold: 0.0001
  verbose: true
Logging:
  cometml_tags:
  log_comment: _thesis_1frame
PostProcessing:
  ax_th: 200.0
  lat_th: 0.3
  match_dims: 3
  single_val_th: 0.2
  skip_if_p_rel: 0.1
  total_th: 0.6
Scaling:
  dx_max: 2.5
  dy_max: 2.5
  in_count_max: 10000.0
  linearisation_buffer: 1.2
  mu_sig_bg:
  - 60.0
  - 120.0
  phot_max: 15000.0
  z_max: 750.0
Simulation:
  bg_perlin_amplitude:
  - 30.0
  - 30.0
  - 30.0
  - 30.0
  bg_perlin_draw_amps: false
  bg_perlin_normalise_amplitudes: true
  bg_perlin_scale:
  - 32
  - 16
  - 8
  - 4
  bg_uniform:
  - 60.0
  - 120.0
  density:
  emitter_av: 15
  emitter_extent:
  - - -0.5
    - 31.5
  - - -0.5
    - 31.5
  - - -750
    - 750
  img_size:
  - 32
  - 32
  intensity_mu_sig:
  - 10000.0
  - 1000.0
  lifetime_avg: 2.0
  photon_range: null
  psf_extent:
  - - -0.5
    - 31.5
  - - -0.5
    - 31.5
  - null
SimulationScheduler:
  cooldown: null
  disabled: true
  factor: null
  max_value: null
  patience: null
  threshold: null
  verbose: null
