Camera:
  baseline: 100.0
  convert2photons: true
  e_per_adu: 45.0
  em_gain: 300.0
  px_size:
  - 100.0
  - 100.0
  qe: 1.0
  read_sigma: 74.4
  spur_noise: 0.002
Evaluation:
  dist_ax:
  dist_lat: 150.0
  dist_vol:
  match_dims: 2
Hardware:
  device: cuda
  device_ix: 0
  device_simulation: cpu
  num_worker_train: 8
  torch_threads: 8
  unix_niceness: 0
  torch_multiprocessing_sharing_strategy: file_system # if you get multiprocessing errors, increase ulimit or set to 'file_system'
HyperParameter:
  arch_param:
    activation: nn.ELU()
    depth:
    depth_shared: 2
    depth_union: 2
    depth_bg:
    init_custom: true
    initial_features: 48
    initial_features_bg:
    inter_features: 48
    norm:
    norm_bg:
    norm_bg_groups:
    norm_groups:
    norm_head:
    norm_head_groups:
    p_dropout:
    pool_mode: StrideConv
    upsample_mode: nearest
    recpt_bg:
    skip_gn_level:
    up_mode: upsample
    use_last_nl:
  architecture: SigmaMUNet
  batch_size: 10
  channels_in: 3
  channels_out:
  chweight_stat:
    - 1.0
    - 0.0
  ds_lifetime:
  epoch_0:
  epochs: 10000
  fgbg_factor:
  grad_mod: true
  emitter_label_photon_min: 100.0
  loss_impl: MixtureModel
  learning_rate_scheduler: StepLR
  learning_rate_scheduler_param:
    step_size: 10
    gamma: 0.9
  moeller_gradient_rescale: false
  opt_param:
    lr: 0.0006
    weight_decay: 0.1
  optimizer: AdamW
  photon_threshold:
  pseudo_ds_size: 1000
  suppress_post_processing: true
InOut:
  calibration_file: data/Calibration/SMLM_Challenge_Beads/Coefficients_Big_ROI/AS-Exp_100nm_3dcal.mat  # cubic spline coefficients
  experiment_out: network/2020-06-26  # main output dir
  model_init:
PostProcessing: LookUp
PostProcessingParam:
  ax_th: 200.0
  lat_th: 0.3
  vol_th:
  match_dims: 2
  skip_if_p_rel: 0.1
  raw_th: 0.1
  total_th: 0.6
Scaling:
  input_scale: 200  # formerly in_count_max
  input_offset: 125.0
  bg_max: 100.0
  phot_max: 20000.0
  z_max: 800.0
Simulation:
  bg_uniform: 90.0
  density:
  emitter_av: 20
  emitter_extent:
  - - -0.5
    - 39.5
  - - -0.5
    - 39.5
  - - -750
    - 750
  img_size:
  - 40
  - 40
  intensity_mu_sig:
  - 10000.0
  - 3000.0
  intensity_th:
  lifetime_avg: 2.0
  mode: samples
  photon_range:
  psf_extent:
  - - -0.5
    - 39.5
  - - -0.5
    - 39.5
  -
  roi_size:
  roi_auto_center: false
  xy_unit: px
TestSet:
  mode:  simulated  # static / simulated
  test_size: 512
  frame_extent:
  - - -0.5
    - 39.5
  - - -0.5
    - 39.5
  - null
  img_size:
    - 40
    - 40

