package:
  name: decode
  version: "0.9.b"

source:
     - path: ../..

build:
  noarch: python
  number: 29

requirements:
  build:
    - python {{ python }}
    - setuptools

  host:
    - python {{ python }}
    - numpy {{ numpy }}

  run:
    - python >=3.6,<4
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - pytorch=1.5
    - torchvision
    - click
    - deprecated
    - h5py
    - joblib
    - matplotlib
    - pandas
    - pytest
    - pyyaml
    - requests
    - scipy
    - seaborn
    - scikit-image
    - scikit-learn
    - spline
    - tensorboard
    - tifffile
    - tqdm

  test:
    requires:
      - python >=3.6,<4
      - pytest
    commands:
      - pytest --pyargs decode

about:
    home: https://rieslab.de
    # dev_url: github url 
    # doc_url: doc url
    # license: GPL-3.0
    # license_family: GPL
    # license_file: {{ SRC_DIR }}/LICENSE
    summary: "High-Density 3D Single-Molecule Localisation Microscopy using Convolutional Neural Networks."
    description: "Experimental. Windows and macOS are CPU only, Linux assumes a CUDA capable GPU. Installation must
    (!) add the proper channels for the PyTorch dependencies: ```conda install decode -c Turagalab -c pytorch -c conda-forge```"
